# Generated by Django 5.1.6 on 2025-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='class_field',
            field=models.CharField(blank=True, db_column='class', max_length=255, null=True),
        ),
    ]
