# Generated by Django 5.1.6 on 2025-04-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_link_class_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='phone',
            field=models.CharField(db_column='phone', max_length=19),
        ),
    ]
